name: 'auto-release'

on:
  workflow_dispatch:
    inputs:
      version:
        type: 'string'
        description: 'Version to release'
        required: true
        default: 'x.y.z'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set package.json version
        uses: HarmvZ/set-package-json-version-action@v0.2.5
        with:
          version: ${{ inputs.version }}
          path: projects/ngx-form

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: '@paddls'
          message: 'release: v${{ inputs.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
